name: fire_library
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  go_router: ^6.0.8
  logger: ^1.1.0

  # Firebase Core
  firebase_core: ^2.6.1

  # Firebase Auth
  firebase_auth: ^4.2.8
  firebase_ui_auth: ^1.1.13
  
  # Firebase Analytics
  firebase_analytics: ^10.1.3  

  # Firebase Firestore
  cloud_firestore: ^4.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
